<div id="navi">
		   <ul>
				<li><a class="zivil" href="zivilrecht/">Zivilrecht</a></li>
				<li><a class="arbeit" href="arbeitsrecht/">Arbeitsrecht</a></li>
				<li><a class="www" href="www-recht/">www-Recht</a></li>
				<li><a class="faq" href="faq/">FAQ</a></li>
				<li><a class="skurril" href="recht_skurriles/">recht Skurriles</a></li>
				<li><a class="insolvent" href="ordnungswidrigkeiten/">Ordnungswidrigkeiten</a></li>
				<li><a class="podcast" href="podcast/">Podcast</a></li>
				<li><a class="mehr" href="mehr_u_6_tdg/">Mehr u. §6 TDG</a></li>
				<li><a class="links" href="links/">Links</a></li>
			</ul>
</div>